// flow-typed signature: f91fe2742e92fd8af20923cfad4fbce1
// flow-typed version: <<STUB>>/get-explicit-type_v^1.0.2/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'get-explicit-type'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'get-explicit-type' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'get-explicit-type/index' {
  declare module.exports: $Exports<'get-explicit-type'>;
}
declare module 'get-explicit-type/index.js' {
  declare module.exports: $Exports<'get-explicit-type'>;
}
